name: ai-utilities
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=0.9.0
  - ansiwrap=0.8.4
  - appdirs=1.4.3
  - astor=0.7.1
  - atomicwrites=1.3.0
  - attrs=19.3.0
  - backcall=0.1.0
  - black=19.10b0
  - blas=1.0
  - bleach
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - colorama=0.4.3
  - cryptography=2.8
  - decorator=4.4.2
  - defusedxml=0.6.0
  - deprecated=1.2.7
  - entrypoints=0.3
  - freetype=2.10.0
  - gast=0.3.3
  - grpcio=1.23.0
  - h5py=2.10.0
  - hdf5=1.10.5
  - idna=2.9
  - importlib-metadata=1.5.0
  - intel-openmp=2019.4
  - ipython=7.13.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg=9
  - jsonschema=3.2.0
  - jupyter_client=6.0.0
  - jupyter_core=4.6.3
  - keras=2.3.1
  - lightgbm=2.3.1
  - lz4-c=1.8.3
  - mako=1.1.0
  - markdown=3.2.1
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - more-itertools=8.2.0
  - mypy_extensions=0.4.3
  - nbclient=0.1.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - nb_conda_kernels
  - notebook=6.0.3
  - numpy=1.18.1
  - olefile=0.46
  - openssl=1.1.1d
  - packaging=20.1
  - pandas=1.0.2
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - papermill=2.0.0
  - parso=0.6.2
  - pathspec=0.7.0
  - pickleshare=0.7.5
  - pillow=7.0.0
  - pip=20.0.2
  - pluggy=0.13.0
  - prometheus_client=0.7.1
  - prompt-toolkit=3.0.4
  - protobuf=3.11.4
  - py=1.8.1
  - pycparser=2.20
  - pygments=2.6.1
  - pygpu=0.7.6
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - pytest=5.4.1
  - pytest-cov
  - pytest-nunit
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-dotenv=0.12.0
  - python_abi=3.7
  - pytz=2019.3
  - pyyaml=5.3
  - pyzmq=19.0.0
  - regex=2020.2.20
  - requests=2.23.0
  - scikit-learn=0.22.2.post1
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=46.0.0
  - six=1.14.0
  - sqlite=3.30.1
  - tenacity=6.1.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - terminado=0.8.3
  - testpath=0.4.4
  - textwrap3=0.9.2
  - theano=1.0.4
  - tk=8.6.10
  - toml=0.10.0
  - tornado=6.0.4
  - toolz=0.10.0
  - tqdm=4.43.0
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.1
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - werkzeug=1.0.0
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - adal==1.2.2
    - applicationinsights==0.11.9
    - azure-common==1.1.25
    - azure-core==1.3.0
    - azure-graphrbac==0.61.1
    - azure-identity==1.3.0
    - azure-mgmt-authorization==0.60.0
    - azure-mgmt-containerregistry==2.8.0
    - azure-mgmt-deploymentmanager==0.2.0
    - azure-mgmt-keyvault==2.1.1
    - azure-mgmt-resource==8.0.1
    - azure-mgmt-storage==8.0.0
    - azure-storage-blob==12.3.0
    - azureml-accel-models==1.1.5
    - azureml-automl-core==1.1.5.1
    - azureml-contrib-functions==1.1.5
    - azureml-contrib-services==1.1.5
    - azureml-core==1.1.5.3
    - azureml-dataprep==1.3.5
    - azureml-dataprep-native==14.1.0
    - azureml-pipeline==1.1.5
    - azureml-pipeline-core==1.1.5
    - azureml-pipeline-steps==1.1.5
    - azureml-telemetry==1.1.5.3
    - azureml-train-automl-client==1.1.5.1
    - azureml-train-core==1.1.5
    - azureml-train-restclients-hyperdrive==1.1.5
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - cloudpickle==1.3.0
    - contextlib2==0.6.0.post1
    - distro==1.4.0
    - docker==4.2.0
    - dotnetcore2==2.1.13
    - flake8==3.7.9
    - flask==1.1.1
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jeepney==0.4.3
    - jmespath==0.9.5
    - jsonpickle==1.3
    - junit-xml==1.9
    - mccabe==0.6.1
    - msal==1.1.0
    - msal-extensions==0.1.3
    - msrest==0.6.11
    - msrestazure==0.6.2
    - ndg-httpsclient==0.5.1
    - oauthlib==3.1.0
    - portalocker==1.5.2
    - pyasn1==0.4.8
    - pycodestyle==2.5.0
    - pylint-junit
    - pytest-nunit
    - pyflakes==2.1.1
    - pyjwt==1.7.1
    - requests-oauthlib==1.3.0
    - resnet==0.1
    - secretstorage==3.1.2
    - urllib3==1.25.8
    - websocket-client==0.57.0
    - wget==3.2
