name: ai-utilities
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip
  - jupyter
  - pytest
  - pytest-cov
  - nb_conda_kernels
  - pylint
  - pandas
  - scikit-learn
  - numpy
  - pip:
    - papermill
    - azureml-core==1.0.85
    - azure-cli==2.0.81
    - pylint-junit
    - pytest-nunit
    - nbconvert
    - junit-xml
    - nbformat
    - python-dotenv
    - PyYAML
