name: ai-utilities
channels:
  - conda-forge
dependencies:
  - python=3.6.2
  - pip
  - jupyter
  - pytest
  - pytest-cov
  - nb_conda_kernels
  - pylint
  - pandas
  - scikit-learn
  - numpy
  - urllib3
  - cudatoolkit==9.0
  - tensorflow-gpu==1.14.0
  - ipywidgets
  - jupyter_contrib_nbextensions
  - matplotlib
  - ipykernel
  - pip:
    - resnet
    - papermill
    - azureml-core==1.0.85
    - azure-cli==2.0.81
    - azure-cli-ml
    - pylint-junit
    - pytest-nunit
    - nbconvert
    - junit-xml
    - nbformat
    - python-dotenv
    - PyYAML
    - msrestazure
    - azure-common
    - lightgbm
    - Deprecated
    - Pillow==6.1.0
    - wget==3.2
    - toolz==0.9.0
    - tqdm==4.32.2
    - azure-core
    - keras==2.2.0
    - azureml-contrib-services
    - locustio==0.11.0
    - prompt-toolkit==2.0.9
    - PyOpenSSL
    - nb-clean
    - azureml-contrib-functions
    - git+https://github.com/microsoft/AI-Utilities.git@deep_learning_2
